config/routes.rb
AngelNest::Application.routes.draw do
  resources :startup_photos

  devise_for :users

  resources :users do
    resources :startups
    resource  :investor
  end

  resources :investors,     :only => :index
  resources :entrepreneurs, :only => :index
  resources :startups do
    resources :messages,    :only => :create, :as => :comments
    resources :proposals,   :only => [:new, :edit, :create, :update]
    member do
      get  'attach_user', :as => :attach_user_to
      post 'attach_user', :as => :attach_user_to
      get  'update_user', :as => :update_user_in
      post 'update_user', :as => :update_user_in
      get  'detach_user', :as => :detach_user_from
      post 'detach_user', :as => :detach_user_from
    end
  end

  match 'startups/:id/profile_details' => 'startups#profile_details',         :via => :get,    :as => :startup_profile_details
  match 'startups/:id/profile_team'    => 'startups#profile_team',            :via => :get,    :as => :startup_profile_team
  match 'startups/:id/photos'          => 'startups#photos',                  :via => :get,    :as => :startup_photos
  match 'startups/:id/upload_photos'   => 'startups#upload_photos',           :via => :get,    :as => :startup_upload_photos

  match 'u/:username'                  => 'users#show',                       :via => :get,    :as => :username

  match 'my/profile'                   => 'users#show',                       :via => :get
  match 'my/home'                      => 'users#home',                       :via => :get
  match 'my/private_messages'          => 'messages#send_private_message',    :via => :post,   :as => :my_private_messages
  match 'my/private_messages/:id'      => 'messages#show_private_message',    :via => :get,    :as => :my_private_message
  match 'my/private_messages/:id'      => 'messages#reply_private_message',   :via => :post,   :as => :my_private_message
  match 'my/private_messages/:id'      => 'messages#archive_private_message', :via => :delete, :as => :my_private_message
  match 'my/message_inboxes(/:type)'   => 'users#message_inboxes',            :via => :get,    :as => :my_message_inbox
  match 'my/micro_posts'               => 'users#add_micro_post',             :via => :post

  match 'my/follow/:target_id'         => 'users#follow_target',              :via => :post,   :as => :follow_target
  match 'my/unfollow/:target_id'       => 'users#unfollow_target',            :via => :post,   :as => :unfollow_target

  root :to => 'users#home'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :proposal
  belongs_to :user, :counter_cache => :messages_count
  belongs_to :target, :polymorphic => true, :counter_cache => :comments_count

  belongs_to :topic, :class_name => 'Message', :foreign_key => 'topic_id'
  has_many :replies, :class_name => 'Message', :foreign_key => 'topic_id'

  attr_accessible :content,
                  :is_private,
                  :target_id,
                  :target_type
  attr_protected  :nil, :as => :internal

  validates :content, :presence => true,
                      :length   => { :maximum => 140 }

  scope :default_order,    order('created_at DESC')
  scope :topics,           where { topic_id == nil }
  scope :replies,          where { topic_id != nil }
  scope :public_only,      where(:is_private => false)
  scope :private_only,     where(:is_private => true)
  scope :read,             where(:is_read => true)
  scope :unread,           where(:is_read => false)
  scope :archived,         where(:is_archived => true)
  scope :unarchived,       where(:is_archived => false)
  scope :with_proposal,    where { proposal_id != nil }
  scope :without_proposal, where { proposal_id == nil }
  scope :micro_posts,      where(:target_id => nil)
  scope :on_users,         where(:target_type => 'User')
  scope :on_startups,      where(:target_type => 'Startup')

  def is_public?
    !is_private
  end

  def is_private?
    !!is_private
  end

  def is_with_proposal?
    !!proposal_id
  end

  def is_without_proposal?
    !proposal_id
  end

  def method_missing(symbol, *args)
    case symbol
      when /^is_(un)?(.*)\?/
        eval "#{$1 ? '!' : '!!'}is_#{$2}"
      when /^mark_as_(un)?(.*)!/
        update_attribute :"is_#{$2}", ($1 ? false : true)
    else
      super
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  inherit_resources

  defaults :collection_name => 'comments'

  belongs_to :startup

  has_scope :p, :default => 1

  before_filter :hide_sidebar, :only => [:show_private_message]
  before_filter :ensure_ownership, :only => [:show_private_message, :reply_private_message]

  def create
    resource = parent.add_comment(current_user, params[:message][:content])

    respond_to do |format|
      format.json { render :json => resource }
      format.html { redirect_to :back }
    end
  end

  def send_private_message
    result = current_user.send_private_message(User.find(params[:message][:users] || params[:users]), params[:message][:content])

    respond_to do |format|
      format.json { render :json => result }
      format.html { redirect_to :back }
    end
  end

  def show_private_message
    @topic = Message.topics.find(params[:id])
  end

  def reply_private_message
    @topic = Message.topics.find(params[:id])
    result = current_user.reply_private_message(@topic, params[:message][:content])

    respond_to do |format|
      format.json { render :json => result }
      format.html { redirect_to :back }
    end
  end

  def archive_private_message
    Message.topics.find(params[:id]).mark_as_archived!

    respond_to do |format|
      format.json { render :json => result }
      format.html do
        flash[:success] = t('text.message_is_archived')
        redirect_to :back
      end
    end
  end
end

app/views/messages/_index.html.slim
- if meta[:new_message?]
  h1= params[:type].titleize
  #new_private_message
    = simple_form_for Message.new, :url => my_private_messages_path do |f|
      .multi_add.input.string data-target="users" data-start_text="#{t('text.enter_recipient_names')}" data-selection_limit="#{Settings.recipient_limit.private_messages}"
        = label_tag :users, t('label.recipients')
        = text_field_tag :users, User.all.map(&:id).join(','), :class => 'string required'
      = f.input :content
      = f.button :submit
    .clear
- if collection.any?
  ul#messages
    - collection.each do |resource|
      li.message= render "messages/#{meta[:show_view] || 'show'}", :resource => resource, :meta => meta
  = show_pagination collection, :param_name => :p

app/views/messages/_new.html.slim
= simple_form_for Message.new, :url => url do |f|
  = f.input :content
  = f.button :submit
  .clear

app/views/messages/_show.html.slim
hr
.message_user
  = render 'users/avatar', :user => resource.user, :meta => {}
.message_container
  .message_meta
    =' link_to resource.user.name, username_path(resource.user.username)
    = time_ago(resource.created_at)
  .message_content
    - if meta[:linkable]
      = link_to resource.content, my_private_message_path(resource)
    - else
      = resource.content

app/views/messages/_show_with_startup.html.slim
hr
.message_user
  = render 'startups/avatar', :startup => resource.proposal.startup
.message_container
  .message_meta
    =' link_to resource.proposal.startup.name, startup_path(resource.proposal.startup)
    = time_ago(resource.created_at)
  .message_meta_secondary
    = "#{t('label.founder')}: "
    =' link_to resource.user.name, username_path(resource.user.username)
    = "#{t('label.from')}: #{resource.user.location}, #{t('label.raise')}: #{number_to_currency(resource.proposal.startup.funds_to_raise)}, #{t('label.stage')}: #{resource.proposal.startup.stage}"
  .message_content
    - if meta[:linkable]
      = link_to resource.content, my_private_message_path(resource)
    - else
      = resource.content

app/views/messages/show_private_message.html.slim
.grid_3
  - if @topic.is_with_proposal?
    = render 'users/proposal_inboxes'
  - else
    = render 'users/message_inboxes'
.grid_9#business_proposal_private_message
  - if @topic.is_with_proposal?
    h1= t('label.business_proposal')
    ul
      li= "#{t('label.submitted_by')}: #{link_to @topic.user.name, user_path(@topic.user)} (#{link_to @topic.proposal.startup.name, startup_path(@topic.proposal.startup)})".html_safe
      li= "#{t('label.submitted_to')}: #{link_to @topic.target.name, user_path(@topic.target)}".html_safe
    hr
    h2= "#{t('label.startup')} #{t('label.details')}"
    = render 'startups/mini_profile', :startup => @topic.proposal.startup, :meta => { :hide_team_members => true, :hide_editable => true }
    hr
    h2= "#{t('label.business_proposal')} #{t('label.details')}"
    = render 'proposals/read_only', :resource => @topic.proposal

  hr
  h2= t('label.actions')
  #action_buttons
    = form_tag do |f|
      = submit_tag t('label.contact_founder'), :rel => 'contact_founder'
    = simple_form_for @topic, :url => my_private_message_path(@topic), :method => :delete do |f|
      = f.button :submit, t('label.not_interested')
    .clear

    #contact_founder
      = simple_form_for Message.new, :url => my_private_messages_path do |f|
        = f.input :users, :as => :hidden, :input_html => { :value => @topic.user.id }
        = f.input :content
        = f.button :submit
      .clear

  hr
  h2= t('label.comments')
  ul#messages
    li.message= render 'show', :resource => @topic, :meta => {}
    - @topic.replies.each do |reply|
      li.message= render 'show', :resource => reply, :meta => {}
  br
  = render 'new', :url => my_private_message_path(@topic)