config/routes.rb
AngelNest::Application.routes.draw do
  resources :startup_photos

  devise_for :users

  resources :users do
    resources :startups
    resource  :investor
  end

  resources :investors,     :only => :index
  resources :entrepreneurs, :only => :index
  resources :startups do
    resources :messages,    :only => :create, :as => :comments
    resources :proposals,   :only => [:new, :edit, :create, :update]
    member do
      get  'attach_user', :as => :attach_user_to
      post 'attach_user', :as => :attach_user_to
      get  'update_user', :as => :update_user_in
      post 'update_user', :as => :update_user_in
      get  'detach_user', :as => :detach_user_from
      post 'detach_user', :as => :detach_user_from
    end
  end

  match 'startups/:id/profile_details' => 'startups#profile_details',         :via => :get,    :as => :startup_profile_details
  match 'startups/:id/profile_team'    => 'startups#profile_team',            :via => :get,    :as => :startup_profile_team
  match 'startups/:id/photos'          => 'startups#photos',                  :via => :get,    :as => :startup_photos
  match 'startups/:id/upload_photos'   => 'startups#upload_photos',           :via => :get,    :as => :startup_upload_photos

  match 'u/:username'                  => 'users#show',                       :via => :get,    :as => :username

  match 'my/profile'                   => 'users#show',                       :via => :get
  match 'my/home'                      => 'users#home',                       :via => :get
  match 'my/private_messages'          => 'messages#send_private_message',    :via => :post,   :as => :my_private_messages
  match 'my/private_messages/:id'      => 'messages#show_private_message',    :via => :get,    :as => :my_private_message
  match 'my/private_messages/:id'      => 'messages#reply_private_message',   :via => :post,   :as => :my_private_message
  match 'my/private_messages/:id'      => 'messages#archive_private_message', :via => :delete, :as => :my_private_message
  match 'my/message_inboxes(/:type)'   => 'users#message_inboxes',            :via => :get,    :as => :my_message_inbox
  match 'my/micro_posts'               => 'users#add_micro_post',             :via => :post

  match 'my/follow/:target_id'         => 'users#follow_target',              :via => :post,   :as => :follow_target
  match 'my/unfollow/:target_id'       => 'users#unfollow_target',            :via => :post,   :as => :unfollow_target

  root :to => 'users#home'

end

app/models/startup.rb
class Startup < ActiveRecord::Base
  include Commentable,
          Followable,
          Paramable

  mount_uploader :logo, LogoUploader

  has_many :photos, :class_name => 'StartupPhoto'

  has_many :startup_users
  has_many :users,      :through => :startup_users
  has_many :members,    :through => :startup_users, :source => :user, :conditions => { 'startup_users.role_identifier' => 'member' }
  has_many :investors,  :through => :startup_users, :source => :user, :conditions => { 'startup_users.role_identifier' => 'investor' }
  has_many :advisors,   :through => :startup_users, :source => :user, :conditions => { 'startup_users.role_identifier' => 'advisor' }
  has_many :incubators, :through => :startup_users, :source => :user, :conditions => { 'startup_users.role_identifier' => 'incubator' }

  has_many :proposals

  attr_accessible :name,
                  :pitch,
                  :funds_to_raise,
                  :stage_identifier,
                  :market_identifier,
                  :location,
                  :description

  accepts_nested_attributes_for :photos, :limit => 5, :allow_destroy => true, :reject_if => :all_blank

  validates :name,              :presence     => true,
                                :uniqueness   => true,
                                :length       => { :within => 4..40 }
  validates :pitch,             :presence     => true,
                                :length       => { :within => 10..140 }
  validates :funds_to_raise,    :presence     => true,
                                :numericality => true
  validates :stage_identifier,  :presence     => true,
                                :inclusion    => { :in => I18n.t('startup.stage_identifiers').keys.map(&:to_s) }
  validates :market_identifier, :presence     => true,
                                :inclusion    => { :in => I18n.t('startup.market_identifiers').keys.map(&:to_s) }
  validates :description,       :presence     => true

  scope :involved, where { startup_users.role_identifier != 'investor' }
  scope :invested, where { startup_users.role_identifier == 'investor' }

  def self.stages
    I18n.t 'startup.stage_identifiers'
  end

  def self.markets
    I18n.t 'startup.market_identifiers'
  end

  def self.roles
    I18n.t 'startup.role_identifiers'
  end

  def stage
    I18n.t "startup.stage_identifiers.#{stage_identifier}"
  end

  def market
    I18n.t "startup.market_identifiers.#{market_identifier}"
  end

  def logo_full
    logo? ? logo : 'startup_460x300.png'
  end

  def logo_thumb
    logo? ? logo.thumb : 'startup_153x100.png'
  end

  def logo_avatar
    logo? ? logo.avatar : 'startup_50x50.png'
  end

  def invite_or_attach_user(role_identifier, attributes)
    user = User.find_by_email(attributes[:email]) || attributes[:email] # && TODO: send an invitation email

    attach_user(user, role_identifier, attributes[:member_title])

    # TODO: remove the confirmation and make the target user to confirm the invite manually
    confirm_user(user, role_identifier)
  end

  def attach_user(user, role_identifier = :member, member_title = '')
    startup_users.create(
      :user_email      => (user.is_a?(User) ? user.email : user),
      :role_identifier => role_identifier.to_s,
      :member_title    => member_title,
    ) unless user_meta(user, role_identifier)
  end

  def confirm_user(user, role_identifier = :member)
    user_meta(user, role_identifier).update_attribute(:confirmed, true)
  end

  def update_user(user, role_identifier = :member, attributes = {})
    user_meta(user, role_identifier).update_attributes(attributes)
  end

  def detach_user(user, role_identifier = :member)
    user_meta(user, role_identifier).destroy
  end

  def founder
    members.first
  end

  def user_meta(user, role_identifier = :member)
    startup_users.where(
      :user_email      => (user.is_a?(User) ? user.email : user),
      :role_identifier => role_identifier.to_s
    ).first
  end

  def member_title(user, role_identifier = :member)
    user_meta(user, role_identifier).member_title
  end

  def user_role(user)
    I18n.t "startup.role_identifiers.#{user_meta(user).role_identifier}"
  end

  def create_proposal(investors = [], attributes = {}, stage = 'draft', private_message = I18n.t('text.default_text_for_proposal_review'))
    raise Exceptions::NotAllowed if proposals.count >= Settings.startup.proposal.limit

    proposal = proposals.create(attributes)
    update_and_submit_proposal(proposal, investors, attributes, stage)
    send_private_message_to_investors(proposal, investors, private_message) if stage == 'submitted'
    proposal
  end

  def update_proposal(proposal, investors = [], attributes = {}, stage = 'draft', private_message = I18n.t('text.default_text_for_proposal_review'))
    proposal.update_attributes(attributes)
    update_and_submit_proposal(proposal, investors, attributes, stage)
    send_private_message_to_investors(proposal, investors, private_message) if stage == 'submitted'
    proposal
  end

  def all_users
    members + investors + advisors + incubators
  end

  private

  def update_and_submit_proposal(proposal, investors, attributes, stage)
    proposal.update_attribute(:proposal_stage_identifier, stage)
    proposal.submit(investors)
    proposal
  end

  def send_private_message_to_investors(proposal, investors, private_message)
    [investors].flatten.each do |investor|
      founder.send_private_message(investor, private_message, :proposal_id => proposal.id)
    end
  end
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  inherit_resources

  belongs_to :user, :optional => true

  has_scope :page, :default => 1

  before_filter :hide_sidebar, :only => [:show, :edit]
  after_filter  :attach_founder_to_startup, :only => :create

  def profile_details
    render :partial => 'startups/profile_details', :locals => { :startup => resource }
  end

  def profile_team
    render :partial => 'startups/profile_team', :locals => { :startup => resource }
  end

  def photos
    render :partial => 'startups/photos', :locals => { :startup => resource }
  end

  def upload_photos

  end

  def attach_user
    if request.post?
      result = resource.invite_or_attach_user(params[:role_identifier], params[:attributes])

      respond_to do |format|
        format.json { render :json => result }
        format.html { redirect_to resource_path(resource) }
      end
    end
  end

  def update_user
    user = User.find(params[:uid])

    if request.post?
      result = resource.update_user(user, params[:role_identifier], params[:attributes])

      respond_to do |format|
        format.json { render :json => result }
        format.html { redirect_to resource_path(resource) }
      end
    else
      @user_meta = resource.user_meta(user)
    end
  end

  def detach_user
    if request.post?
      result = resource.detach_user(User.find(params[:uid]), params[:role_identifier])

      respond_to do |format|
        format.json { render :json => result }
        format.html { redirect_to resource_path(resource) }
      end
    end
  end

  private

  def attach_founder_to_startup
    if resource.persisted?
      resource.attach_user(parent, :member, t('label.founder'))
      resource.confirm_user(parent)
    end
  end
end

app/views/startups/_add_user_link.html.slim
- if startup.founder == current_user
  = render 'shared/editable', :add_element => true, :text => t('label.add'), :url => attach_user_to_startup_path(startup, :role_identifier => role_identifier)

app/views/startups/_comments.html.slim
= render 'messages/new', :url => startup_comments_path(resource)
= render 'messages/index', :collection => resource.comments.page(params[:p]), :meta => {}

app/views/startups/_form.html.slim
= simple_form_for resource, :url => submit_path, :validate => true do |f|
  = f.input :name
  = f.input :pitch
  = f.input :funds_to_raise
  = f.input :stage_identifier,  :collection => Startup.stages,  :value_method => :first, :label_method => :second
  = f.input :market_identifier, :collection => Startup.markets, :value_method => :first, :label_method => :second
  = f.input :logo, :as => :file
  = f.input :logo_cache, :as => :hidden
  - if resource.logo?
    = f.input :remove_logo, :as => :boolean
    .input
      = label_tag ''
      = image_tag(resource.logo_thumb)
  = f.input :description
  = f.button :submit

app/views/startups/_mini_profile.html.slim
- if startup.founder == current_user && !meta[:hide_editable]
  = render 'shared/editable', :edit_target => '#profile_details'

.mini_profile.inline_edtiable_container
  #profile_details data-target_link="#{startup_profile_details_path(startup)}"
    = render 'startups/profile_details', :startup => startup
  .clear

  - unless meta[:hide_team_members]
    hr
    #profile_team
      = render 'startups/profile_team', :startup => startup

app/views/startups/_profile_details.html.slim
.profile_pic
  = image_tag(startup.logo_thumb)

.profile_meta
  h2= startup.name
  ul
    li= startup.location
    li= startup.market
    li.pitch= startup.pitch

.profile_details
  = render 'shared/popularity_metrics', :resource => startup
  hr
  p= startup.description

app/views/startups/_profile_team.html.slim
.team.inline_popup data-target_link="#{startup_profile_team_path(startup)}" data-edit_target="#profile_team"
    h2= t('label.members')
    = render 'startups/add_user_link', :startup => startup, :role_identifier => 'member'
    = render 'users/index', :collection => startup.members, :meta => { :removable => true, :editable => true, :parent => startup, :role_identifier => 'member' }
    .clear

.team
  h2= t('label.investors')
  = render 'startups/add_user_link', :startup => startup, :role_identifier => 'investor'
  = render 'users/index', :collection => startup.investors, :meta => { :removable => true, :editable => true, :parent => startup, :role_identifier => 'investor' }
  .clear

.team
  h2= t('label.advisors')
  = render 'startups/add_user_link', :startup => startup, :role_identifier => 'advisor'
  = render 'users/index', :collection => startup.advisors, :meta => { :removable => true, :editable => true, :parent => startup, :role_identifier => 'advisor' }
  .clear

.team
  h2= t('label.incubators')
  = render 'startups/add_user_link', :startup => startup, :role_identifier => 'incubator'
  = render 'users/index', :collection => startup.incubators, :meta => { :removable => true, :editable => true, :parent => startup, :role_identifier => 'incubator' }
  .clear

app/views/startups/attach_user.html.slim
= form_tag attach_user_to_startup_path(resource, :role_identifier => params[:role_identifier]), :class => 'inline' do
  .input.string.required
    = label_tag      :'attributes[name]', "<abbr title='required'>*</abbr> #{t('label.name')}".html_safe
    = text_field_tag :'attributes[name]'
  .input.string
    = label_tag      :'attributes[member_title]', t('label.title')
    = text_field_tag :'attributes[member_title]'
  .input.string
    = label_tag      :'attributes[email]', "<abbr title='required'>*</abbr> #{t('label.email')}".html_safe
    = text_field_tag :'attributes[email]'
  = submit_tag t('label.add')
  .clear

app/views/startups/detach_user.html.slim
= form_tag detach_user_from_startup_path(resource, :role_identifier => params[:role_identifier], :uid => params[:uid]), :class => 'inline' do
  = submit_tag t('label.confirm_deletion')
  .clear

app/views/startups/edit.html.slim
h1
  =' t('label.edit')
  = t('label.startup_profile')

= render 'form', :submit_path => resource_path(resource)

app/views/startups/index.html.slim
ul.resource_list.startup_list
  - collection.each do |startup|
    li.mini_profile
      hr

      .profile_pic
        = render 'avatar', :startup => startup

      .profile_meta
        h2= link_to startup.name, startup_path(startup)
        ul
          li= startup.pitch
          li.secondary
            = "#{t('label.founder')}: "
            =' link_to startup.founder.name, username_path(startup.founder.username)
            = "#{t('label.from')}: #{startup.founder.location}, #{t('label.raise')}: #{number_to_currency(startup.funds_to_raise)}, #{t('label.stage')}: #{startup.stage}"

      .profile_metrics
        .follow_button= follow_button(startup)

= show_pagination collection

app/views/startups/new.html.slim
h1
  =' t('label.create')
  = t('label.startup_profile')

= render 'form', :submit_path => user_startups_path

app/views/startups/show.html.slim
.grid_6
  = render 'mini_profile', :startup => resource, :meta => {}
.grid_6.inline_edtiable_container
  - if resource.founder == current_user
    = render 'shared/editable', :edit_target => '#gallery', :url => startup_upload_photos_path(resource)
  h2 ...
  = render 'photos', :startup => resource
  = render 'comments', :resource => resource

- if resource.founder == current_user
  .grid_12
    hr
    h2= t('label.business_proposals')
    ul
      - if resource.proposals.any?
        - resource.proposals.each_with_index do |proposal, index|
          li= link_to "#{t('label.business_proposal')} #{index + 1} (#{t("startup.proposal_stage_identifiers.#{proposal.proposal_stage_identifier}")})", edit_startup_proposal_path(resource, proposal)
      - else
        li.create_new= link_to t('label.create_new'), new_startup_proposal_path(resource)

app/views/startups/update_user.html.slim
= form_tag update_user_in_startup_path(resource, :role_identifier => params[:role_identifier], :uid => params[:uid]), :class => 'inline' do
  .input.string
    = label_tag      :'attributes[member_title]', t('label.title')
    = text_field_tag :'attributes[member_title]', @user_meta.member_title
  = submit_tag t('label.update')
  .clear

app/views/startups/upload_photos.html.slim
= simple_nested_form_for resource, :url => startup_path(resource) do |f|
  = f.simple_fields_for :photos, resource.photos.build do |p|
    = p.input :photo, :as => :file
    = p.input :photo_cache, :as => :hidden

  - resource.photos.all.each do |photo|
    = f.simple_fields_for :photos, photo do |p|
      = label_tag ''
      = p.link_to_remove t('label.delete_the_image_below'),
      = p.input :photo_cache, :as => :hidden
      .input
        = label_tag ''
        = image_tag(photo.photo.slideshow)
  = f.button :submit
.clear