config/routes.rb
AngelNest::Application.routes.draw do
  resources :startup_photos

  devise_for :users

  resources :users do
    resources :startups
    resource  :investor
  end

  resources :investors,     :only => :index
  resources :entrepreneurs, :only => :index
  resources :startups do
    resources :messages,    :only => :create, :as => :comments
    resources :proposals,   :only => [:new, :edit, :create, :update]
    member do
      get  'attach_user', :as => :attach_user_to
      post 'attach_user', :as => :attach_user_to
      get  'update_user', :as => :update_user_in
      post 'update_user', :as => :update_user_in
      get  'detach_user', :as => :detach_user_from
      post 'detach_user', :as => :detach_user_from
    end
  end

  match 'startups/:id/profile_details' => 'startups#profile_details',         :via => :get,    :as => :startup_profile_details
  match 'startups/:id/profile_team'    => 'startups#profile_team',            :via => :get,    :as => :startup_profile_team
  match 'startups/:id/photos'          => 'startups#photos',                  :via => :get,    :as => :startup_photos
  match 'startups/:id/upload_photos'   => 'startups#upload_photos',           :via => :get,    :as => :startup_upload_photos

  match 'u/:username'                  => 'users#show',                       :via => :get,    :as => :username

  match 'my/profile'                   => 'users#show',                       :via => :get
  match 'my/home'                      => 'users#home',                       :via => :get
  match 'my/private_messages'          => 'messages#send_private_message',    :via => :post,   :as => :my_private_messages
  match 'my/private_messages/:id'      => 'messages#show_private_message',    :via => :get,    :as => :my_private_message
  match 'my/private_messages/:id'      => 'messages#reply_private_message',   :via => :post,   :as => :my_private_message
  match 'my/private_messages/:id'      => 'messages#archive_private_message', :via => :delete, :as => :my_private_message
  match 'my/message_inboxes(/:type)'   => 'users#message_inboxes',            :via => :get,    :as => :my_message_inbox
  match 'my/micro_posts'               => 'users#add_micro_post',             :via => :post

  match 'my/follow/:target_id'         => 'users#follow_target',              :via => :post,   :as => :follow_target
  match 'my/unfollow/:target_id'       => 'users#unfollow_target',            :via => :post,   :as => :unfollow_target

  root :to => 'users#home'

end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base
  include Commentable,
          Followable

  devise :database_authenticatable,
         :token_authenticatable,
         :omniauthable,
         :confirmable,
         :recoverable,
         :registerable,
         :rememberable,
         :trackable,
         :validatable

  attr_readonly :messages_count

  attr_accessor   :login
  attr_accessible :login,
                  :username,
                  :name,
                  :email,
                  :password,
                  :password_confirmation,
                  :remember_me

  has_many :messages, :order => 'created_at DESC'

  has_one  :investor_profile

  has_and_belongs_to_many :proposals, :join_table => :proposal_for_investors

  has_many :startup_users, :foreign_key => 'user_email', :primary_key => 'email'
  has_many :startups, :through => :startup_users

  has_many :target_followed,   :class_name => 'TargetFollower', :as => :follower
  has_many :users_followed,    :through => :target_followed, :source => :target, :source_type => 'User'
  has_many :startups_followed, :through => :target_followed, :source => :target, :source_type => 'Startup'

  validates :username, :presence     => true,
                       :uniqueness   => { :case_sensitive => false },
                       :length       => { :within => 4..20 },
                       :format       => { :with => /^[A-Za-z0-9_]+$/ }
  validates :name,     :presence     => true,
                       :length       => { :within => 4..30 }

  scope :new_users,     joins { [startup_users.outer, investor_profile.outer] }.where { (startup_users.user_email == nil) & (investor_profiles.user_id == nil) }
  scope :entrepreneurs, joins { startup_users }.where { startup_users.user_email != nil }
  scope :investors,     joins { investor_profile }.where { investor_profiles.user_id != nil }

  before_save :email_nomarlisation

  def incoming_messages
    comments.private_only.topics
  end

  def outgoing_messages
    messages.on_users.private_only.topics
  end

  def inbox_messages
    incoming_messages.without_proposal.unarchived
  end

  def sent_messages
    outgoing_messages.without_proposal
  end

  def archived_messages
    incoming_messages.without_proposal.archived
  end

  def inbox_proposals
    incoming_messages.with_proposal.unarchived
  end

  def sent_proposals
    outgoing_messages.with_proposal
  end

  def archived_proposals
    incoming_messages.with_proposal.archived
  end

  def has_new_messages?
    inbox_messages.unread.any?
  end

  def has_new_proposals?
    inbox_proposals.unread.any?
  end

  def is_admin?
    !!is_admin
  end

  def is_new_user?
    !is_entrepreneur? && !is_investor?
  end

  def is_entrepreneur?
    startups.present?
  end

  def is_investor?
    investor_profile.present?
  end

  def avatar(size = 80)
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}?s=#{size}"
  end

  def send_private_message(target_user, content, extras = {})
    messages.create!({
      :content     => content,
      :is_private  => true,
      :target_id   => target_user.id,
      :target_type => 'User'
    }.merge(extras), :as => :internal) && reload
  end

  def reply_private_message(topic, content, extras = {})
    messages.create!({
      :content     => content,
      :is_private  => true,
      :target_id   => topic.user.id,
      :target_type => 'User',
      :topic_id    => topic.id
    }.merge(extras), :as => :internal) && reload
  end

  def add_micro_post(content)
    unless content.blank?
      messages.create(:content => content) && reload
      true
    else
      false
    end
  end

  def micro_posts
    messages.micro_posts
  end

  def follow(target)
    target.target_followers.create(
      :follower_id   => id,
      :follower_type => 'User'
    ) && reload unless target == self || target.nil?
  end

  def unfollow(target)
    target.target_followers.where(
      :follower_id   => id,
      :follower_type => 'User'
    ).first.try(:destroy) && reload unless target.nil?
  end

  def is_following?(target)
    return false if target.nil?
    !!target_followed.where(:target_id => target.id, :target_type => target.class.name).first
  end

  def followed
    users_followed + startups_followed
  end

  def followed_micro_posts
    Message.where(:target_id => nil, :user_id => users_followed_ids + [id]).default_order
  end

  protected

  # Devise's support for login using the :login virtual attribute
  # https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign_in-using-their-username-or-email-address
  class << self
    def find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      login      = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    end

    def send_reset_password_instructions(attributes={})
      recoverable = find_recoverable_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
      recoverable.send_reset_password_instructions if recoverable.persisted?
      recoverable
    end

    def find_recoverable_or_initialize_with_errors(required_attributes, attributes, error=:invalid)
      (case_insensitive_keys || []).each { |k| attributes[k].try(:downcase!) }

      attributes = attributes.slice(*required_attributes)
      attributes.delete_if { |key, value| value.blank? }

      if attributes.size == required_attributes.size
        if attributes.has_key?(:login)
           login = attributes.delete(:login)
           record = find_record(login)
        else
          record = where(attributes).first
        end
      end

      unless record
        record = new

        required_attributes.each do |key|
          value = attributes[key]
          record.send("#{key}=", value)
          record.errors.add(key, value.present? ? error : :blank)
        end
      end
      record
    end

    def find_record(login)
      where(["username = :value OR email = :value", { :value => login }]).first
    end
  end

  private

  def email_nomarlisation
    self.email = email.strip.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  inherit_resources

  has_scope :page, :default => 1

  before_filter :hide_sidebar, :only => [:show, :message_inboxes]

  def index
    respond_to do |format|
      format.json { render :json => collection.for_auto_suggest }
      format.html { render 'users/_index', :locals => { :meta => {} } }
    end
  end

  def home
    @micro_posts = resource.followed_micro_posts.page(params[:p])
  end

  def show
    @micro_posts = resource.micro_posts.page(params[:p])
  end

  def message_inboxes
    message_type = params[:type].try(:to_sym)

    @messages = case message_type
      when :inbox_messages     then current_user.inbox_messages
      when :sent_messages      then current_user.sent_messages
      when :archived_messages  then current_user.archived_messages
      when :inbox_proposals    then current_user.inbox_proposals
      when :sent_proposals     then current_user.sent_proposals
      when :archived_proposals then current_user.archived_proposals
      else redirect_to my_message_inbox_path(:inbox_messages)
    end

    case message_type
      when /_messages/  then render 'message_inboxes'
      when /_proposals/ then render 'proposal_inboxes'
    end
  end

  def add_micro_post
    result = current_user.add_micro_post(params[:message][:content])

    respond_to do |format|
      format.json { render :json => result }
      format.html { redirect_to :back }
    end
  end

  def follow_target
    result = current_user.follow(target)

    respond_to do |format|
      format.json { render :json => result }
      format.html { redirect_to :back }
    end
  end

  def unfollow_target
    result = current_user.unfollow(target)

    respond_to do |format|
      format.json { render :json => result }
      format.html { redirect_to :back }
    end
  end

  private

  def collection
    User.page(params[:page])
  end

  def resource
    if params.key?(:username)
      User.find_by_username(params[:username])
    elsif params.key?(:id)
      super
    else
      current_user
    end
  end

  def target
    params[:target_type].constantize.find(params[:target_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def find_geo_location
    GeoLocation.find(request.remote_ip)
  end

  def detected_country;         find_geo_location[:country]                     end
  def detected_country_code;    find_geo_location[:country_code]                end
  def detected_city;            find_geo_location[:city]                        end
  def detected_region;          find_geo_location[:region]                      end
  def detected_timezone;        find_geo_location[:timezone]                    end
  def detected_city_and_region; [detected_city, detected_region].compact * ', ' end

  def show_user_roles(user)
    roles = []
    roles << t('label.entrepreneur') if user.is_entrepreneur?
    roles << t('label.investor') if user.is_investor?

    if roles.any?
      " (#{roles * ', '})".html_safe
    else
      ''
    end
  end
end

app/views/users/_avatar.html.slim
div style="height: #{meta[:height] || meta[:size] || 50}px; width: #{meta[:width] || meta[:size] || 50}px; overflow: hidden;"
  = link_to image_tag(user.avatar(meta[:width] || meta[:size] || 50), :alt => user.username), username_path(user.username)

app/views/users/_index.html.slim
ul.resource_list.user_list
  - collection.each do |user|
    li.mini_profile data-target_link="#{startup_profile_team_path(meta[:parent]) if meta[:parent]}" data-edit_target="#profile_team"
      - unless meta[:role_identifier]
        hr

      .profile_pic
        = render 'users/avatar', :user => user, :meta => {}

      .profile_meta
        h2= link_to user.name, username_path(user.username)
        ul
          - if meta[:role_identifier]
            li= "#{meta[:parent].user_meta(user, meta[:role_identifier]).member_title}&nbsp;".html_safe
          - else
            li.introduction= user.introduction
            li.location= user.location

      - if meta[:role_identifier]
        .inline_editable
          - if meta[:editable] && meta[:parent].founder == current_user
            = render 'shared/editable', :text => t('label.update'), :url => eval("update_user_in_#{meta[:parent].class.name.downcase}_path(parent, :role_identifier => :#{meta[:role_identifier]}, :uid => #{user.id})")
          - if meta[:removable] && meta[:parent].founder == current_user
            = render 'shared/editable', :text => t('label.remove'), :url => eval("detach_user_from_#{meta[:parent].class.name.downcase}_path(parent, :role_identifier => :#{meta[:role_identifier]}, :uid => #{user.id})")
      - else
        .profile_metrics
          .follow_button= follow_button(user)

= show_pagination collection

app/views/users/_invested_in.html.slim
hr

h3= t('label.invested_in')
- if user.startups.invested.any?
  = render 'ventures/mini_index', :collection => user.startups.invested, :user => user, :can_create_new => false
- else
  = t('text.no_invested_startups_found')

app/views/users/_investor.html.slim
hr

h3= t('label.investor')
- if user.is_investor?
  = render 'ventures/mini_index', :collection => [user], :user => user, :can_create_new => false
- else
  p
    =' t('text.not_an_investor')
    = link_to t('label.apply_now'), new_user_investor_path(user)

app/views/users/_message_inboxes.html.slim
= render 'users/mini_profile', :user => current_user, :meta => {}

hr
h3= t('label.private_messages')
ul
 li= link_to_current t('label.inbox_messages'), my_message_inbox_path(:inbox_messages)
 li= link_to_current t('label.sent_messages') , my_message_inbox_path(:sent_messages)
 li= link_to_current t('label.archived_messages') , my_message_inbox_path(:archived_messages)

app/views/users/_mini_profile.html.slim
.mini_profile
  .profile_pic
    = render 'users/avatar', :user => user, :meta => {}

  .profile_meta
    h2
      = link_to user.name, username_path(user.username)
      = show_user_roles(user) if meta[:show_user_roles]
    ul
      li= user.location

  .profile_details
    = render 'shared/popularity_metrics', :resource => user
  .clear

app/views/users/_proposal_inboxes.html.slim
= render 'users/mini_profile', :user => current_user, :meta => {}

hr
h3= t('label.startup_proposals')
ul
  li= link_to_current t('label.inbox_proposals') , my_message_inbox_path(:inbox_proposals)
  li= link_to_current t('label.sent_proposals') , my_message_inbox_path(:sent_proposals)
  li= link_to_current t('label.archived_proposals') , my_message_inbox_path(:archived_proposals)

app/views/users/_startups.html.slim
hr

h3= t('label.startups')
- if user.is_entrepreneur?
  = render 'ventures/mini_index', :collection => user.startups.involved, :user => user, :can_create_new => true
- else
  p
    =' t('text.have_no_startups')
    = link_to t('label.create_one_now'), new_user_startup_path(user)

app/views/users/home.html.slim
= render 'messages/new', :url => my_micro_posts_path
= render 'messages/index', :collection => @micro_posts, :meta => {}

app/views/users/message_inboxes.html.slim
.grid_3
  = render 'users/message_inboxes'
.grid_9
  = render 'messages/index', :collection => @messages, :meta => { :linkable => true, :new_message? => true }

app/views/users/proposal_inboxes.html.slim
.grid_3
  = render 'users/proposal_inboxes'
.grid_9
  = render 'messages/index', :collection => @messages, :meta => { :linkable => true, :show_view => 'show_with_startup' }

app/views/users/show.html.slim
.grid_6
  = render 'users/mini_profile', :user => resource, :meta => { :show_user_roles => true }
  = render 'users/startups', :user => resource if resource.is_entrepreneur?
  = render 'users/invested_in', :user => resource if resource.is_investor?

.grid_6
  = render 'messages/index', :collection => @micro_posts, :meta => {}